
name: Deploy Image CD

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to deploy'
        required: true
        
env:
  PYTHON_FLASK_RESTAPI_POC_IMAGE_TAG: ${{ github.event.inputs.version }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
        
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    - name: Download task definition
      run: |
        aws ecs describe-task-definition --task-definition 	python-flask-restapi-poc --query taskDefinition > task-definition.json
        
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      
    - name: Fill in the new image ID in the Amazon ECS task definition
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: python-flask-restapi-poc
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition.json
        container-name: python-flask-restapi-poc
        image: $ECR_REGISTRY/$ECR_REPOSITORY:$PYTHON_FLASK_RESTAPI_POC_IMAGE_TAG

    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: flask-restapi-poc
        cluster: ecs-python-flask-poc-cluster
        wait-for-service-stability: true
